In [1]:
import numpy as np

# Euler angles (in radians)
roll = np.radians(30)   # φ
pitch = np.radians(45)  # θ
yaw = np.radians(60)    # ψ

# Rotation matrix about X (roll)
Rx = np.array([
    [1, 0, 0],
    [0, np.cos(roll), -np.sin(roll)],
    [0, np.sin(roll), np.cos(roll)]
])

# Rotation matrix about Y (pitch)
Ry = np.array([
    [np.cos(pitch), 0, np.sin(pitch)],
    [0, 1, 0],
    [-np.sin(pitch), 0, np.cos(pitch)]
])

# Rotation matrix about Z (yaw)
Rz = np.array([
    [np.cos(yaw), -np.sin(yaw), 0],
    [np.sin(yaw), np.cos(yaw), 0],
    [0, 0, 1]
])

# Combined rotation (ZYX order)
R = Rz @ Ry @ Rx

print("Rotation Matrix:")
print(R)

Rotation Matrix:
[[ 0.35355339 -0.5732233   0.73919892]
 [ 0.61237244  0.73919892  0.28033009]
 [-0.70710678  0.35355339  0.61237244]]
